// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mini2.proto

#include "mini2.pb.h"
#include "mini2.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace mini2 {

static const char* NodeService_method_names[] = {
  "/mini2.NodeService/SubmitQuery",
  "/mini2.NodeService/FetchChunk",
  "/mini2.NodeService/ForwardQuery",
  "/mini2.NodeService/CancelQuery",
};

std::unique_ptr< NodeService::Stub> NodeService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< NodeService::Stub> stub(new NodeService::Stub(channel, options));
  return stub;
}

NodeService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SubmitQuery_(NodeService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FetchChunk_(NodeService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ForwardQuery_(NodeService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CancelQuery_(NodeService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status NodeService::Stub::SubmitQuery(::grpc::ClientContext* context, const ::mini2::QueryRequest& request, ::mini2::ChunkResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mini2::QueryRequest, ::mini2::ChunkResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SubmitQuery_, context, request, response);
}

void NodeService::Stub::async::SubmitQuery(::grpc::ClientContext* context, const ::mini2::QueryRequest* request, ::mini2::ChunkResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mini2::QueryRequest, ::mini2::ChunkResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SubmitQuery_, context, request, response, std::move(f));
}

void NodeService::Stub::async::SubmitQuery(::grpc::ClientContext* context, const ::mini2::QueryRequest* request, ::mini2::ChunkResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SubmitQuery_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mini2::ChunkResponse>* NodeService::Stub::PrepareAsyncSubmitQueryRaw(::grpc::ClientContext* context, const ::mini2::QueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mini2::ChunkResponse, ::mini2::QueryRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SubmitQuery_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mini2::ChunkResponse>* NodeService::Stub::AsyncSubmitQueryRaw(::grpc::ClientContext* context, const ::mini2::QueryRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSubmitQueryRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status NodeService::Stub::FetchChunk(::grpc::ClientContext* context, const ::mini2::ChunkRequest& request, ::mini2::ChunkResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mini2::ChunkRequest, ::mini2::ChunkResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FetchChunk_, context, request, response);
}

void NodeService::Stub::async::FetchChunk(::grpc::ClientContext* context, const ::mini2::ChunkRequest* request, ::mini2::ChunkResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mini2::ChunkRequest, ::mini2::ChunkResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FetchChunk_, context, request, response, std::move(f));
}

void NodeService::Stub::async::FetchChunk(::grpc::ClientContext* context, const ::mini2::ChunkRequest* request, ::mini2::ChunkResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FetchChunk_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mini2::ChunkResponse>* NodeService::Stub::PrepareAsyncFetchChunkRaw(::grpc::ClientContext* context, const ::mini2::ChunkRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mini2::ChunkResponse, ::mini2::ChunkRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FetchChunk_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mini2::ChunkResponse>* NodeService::Stub::AsyncFetchChunkRaw(::grpc::ClientContext* context, const ::mini2::ChunkRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFetchChunkRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status NodeService::Stub::ForwardQuery(::grpc::ClientContext* context, const ::mini2::ForwardRequest& request, ::mini2::ForwardResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mini2::ForwardRequest, ::mini2::ForwardResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ForwardQuery_, context, request, response);
}

void NodeService::Stub::async::ForwardQuery(::grpc::ClientContext* context, const ::mini2::ForwardRequest* request, ::mini2::ForwardResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mini2::ForwardRequest, ::mini2::ForwardResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ForwardQuery_, context, request, response, std::move(f));
}

void NodeService::Stub::async::ForwardQuery(::grpc::ClientContext* context, const ::mini2::ForwardRequest* request, ::mini2::ForwardResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ForwardQuery_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mini2::ForwardResponse>* NodeService::Stub::PrepareAsyncForwardQueryRaw(::grpc::ClientContext* context, const ::mini2::ForwardRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mini2::ForwardResponse, ::mini2::ForwardRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ForwardQuery_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mini2::ForwardResponse>* NodeService::Stub::AsyncForwardQueryRaw(::grpc::ClientContext* context, const ::mini2::ForwardRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncForwardQueryRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status NodeService::Stub::CancelQuery(::grpc::ClientContext* context, const ::mini2::CancelRequest& request, ::mini2::CancelResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mini2::CancelRequest, ::mini2::CancelResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CancelQuery_, context, request, response);
}

void NodeService::Stub::async::CancelQuery(::grpc::ClientContext* context, const ::mini2::CancelRequest* request, ::mini2::CancelResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mini2::CancelRequest, ::mini2::CancelResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CancelQuery_, context, request, response, std::move(f));
}

void NodeService::Stub::async::CancelQuery(::grpc::ClientContext* context, const ::mini2::CancelRequest* request, ::mini2::CancelResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CancelQuery_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mini2::CancelResponse>* NodeService::Stub::PrepareAsyncCancelQueryRaw(::grpc::ClientContext* context, const ::mini2::CancelRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mini2::CancelResponse, ::mini2::CancelRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CancelQuery_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mini2::CancelResponse>* NodeService::Stub::AsyncCancelQueryRaw(::grpc::ClientContext* context, const ::mini2::CancelRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCancelQueryRaw(context, request, cq);
  result->StartCall();
  return result;
}

NodeService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::mini2::QueryRequest, ::mini2::ChunkResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](NodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mini2::QueryRequest* req,
             ::mini2::ChunkResponse* resp) {
               return service->SubmitQuery(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::mini2::ChunkRequest, ::mini2::ChunkResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](NodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mini2::ChunkRequest* req,
             ::mini2::ChunkResponse* resp) {
               return service->FetchChunk(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::mini2::ForwardRequest, ::mini2::ForwardResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](NodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mini2::ForwardRequest* req,
             ::mini2::ForwardResponse* resp) {
               return service->ForwardQuery(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::mini2::CancelRequest, ::mini2::CancelResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](NodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mini2::CancelRequest* req,
             ::mini2::CancelResponse* resp) {
               return service->CancelQuery(ctx, req, resp);
             }, this)));
}

NodeService::Service::~Service() {
}

::grpc::Status NodeService::Service::SubmitQuery(::grpc::ServerContext* context, const ::mini2::QueryRequest* request, ::mini2::ChunkResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::FetchChunk(::grpc::ServerContext* context, const ::mini2::ChunkRequest* request, ::mini2::ChunkResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::ForwardQuery(::grpc::ServerContext* context, const ::mini2::ForwardRequest* request, ::mini2::ForwardResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::CancelQuery(::grpc::ServerContext* context, const ::mini2::CancelRequest* request, ::mini2::CancelResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace mini2
#include <grpcpp/ports_undef.inc>

