// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mini2.proto
#ifndef GRPC_mini2_2eproto__INCLUDED
#define GRPC_mini2_2eproto__INCLUDED

#include "mini2.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace mini2 {

class NodeService final {
 public:
  static constexpr char const* service_full_name() {
    return "mini2.NodeService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SubmitQuery(::grpc::ClientContext* context, const ::mini2::QueryRequest& request, ::mini2::ChunkResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mini2::ChunkResponse>> AsyncSubmitQuery(::grpc::ClientContext* context, const ::mini2::QueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mini2::ChunkResponse>>(AsyncSubmitQueryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mini2::ChunkResponse>> PrepareAsyncSubmitQuery(::grpc::ClientContext* context, const ::mini2::QueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mini2::ChunkResponse>>(PrepareAsyncSubmitQueryRaw(context, request, cq));
    }
    virtual ::grpc::Status FetchChunk(::grpc::ClientContext* context, const ::mini2::ChunkRequest& request, ::mini2::ChunkResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mini2::ChunkResponse>> AsyncFetchChunk(::grpc::ClientContext* context, const ::mini2::ChunkRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mini2::ChunkResponse>>(AsyncFetchChunkRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mini2::ChunkResponse>> PrepareAsyncFetchChunk(::grpc::ClientContext* context, const ::mini2::ChunkRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mini2::ChunkResponse>>(PrepareAsyncFetchChunkRaw(context, request, cq));
    }
    virtual ::grpc::Status ForwardQuery(::grpc::ClientContext* context, const ::mini2::ForwardRequest& request, ::mini2::ForwardResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mini2::ForwardResponse>> AsyncForwardQuery(::grpc::ClientContext* context, const ::mini2::ForwardRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mini2::ForwardResponse>>(AsyncForwardQueryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mini2::ForwardResponse>> PrepareAsyncForwardQuery(::grpc::ClientContext* context, const ::mini2::ForwardRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mini2::ForwardResponse>>(PrepareAsyncForwardQueryRaw(context, request, cq));
    }
    virtual ::grpc::Status CancelQuery(::grpc::ClientContext* context, const ::mini2::CancelRequest& request, ::mini2::CancelResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mini2::CancelResponse>> AsyncCancelQuery(::grpc::ClientContext* context, const ::mini2::CancelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mini2::CancelResponse>>(AsyncCancelQueryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mini2::CancelResponse>> PrepareAsyncCancelQuery(::grpc::ClientContext* context, const ::mini2::CancelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mini2::CancelResponse>>(PrepareAsyncCancelQueryRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SubmitQuery(::grpc::ClientContext* context, const ::mini2::QueryRequest* request, ::mini2::ChunkResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SubmitQuery(::grpc::ClientContext* context, const ::mini2::QueryRequest* request, ::mini2::ChunkResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void FetchChunk(::grpc::ClientContext* context, const ::mini2::ChunkRequest* request, ::mini2::ChunkResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void FetchChunk(::grpc::ClientContext* context, const ::mini2::ChunkRequest* request, ::mini2::ChunkResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ForwardQuery(::grpc::ClientContext* context, const ::mini2::ForwardRequest* request, ::mini2::ForwardResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ForwardQuery(::grpc::ClientContext* context, const ::mini2::ForwardRequest* request, ::mini2::ForwardResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void CancelQuery(::grpc::ClientContext* context, const ::mini2::CancelRequest* request, ::mini2::CancelResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CancelQuery(::grpc::ClientContext* context, const ::mini2::CancelRequest* request, ::mini2::CancelResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mini2::ChunkResponse>* AsyncSubmitQueryRaw(::grpc::ClientContext* context, const ::mini2::QueryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mini2::ChunkResponse>* PrepareAsyncSubmitQueryRaw(::grpc::ClientContext* context, const ::mini2::QueryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mini2::ChunkResponse>* AsyncFetchChunkRaw(::grpc::ClientContext* context, const ::mini2::ChunkRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mini2::ChunkResponse>* PrepareAsyncFetchChunkRaw(::grpc::ClientContext* context, const ::mini2::ChunkRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mini2::ForwardResponse>* AsyncForwardQueryRaw(::grpc::ClientContext* context, const ::mini2::ForwardRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mini2::ForwardResponse>* PrepareAsyncForwardQueryRaw(::grpc::ClientContext* context, const ::mini2::ForwardRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mini2::CancelResponse>* AsyncCancelQueryRaw(::grpc::ClientContext* context, const ::mini2::CancelRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mini2::CancelResponse>* PrepareAsyncCancelQueryRaw(::grpc::ClientContext* context, const ::mini2::CancelRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SubmitQuery(::grpc::ClientContext* context, const ::mini2::QueryRequest& request, ::mini2::ChunkResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mini2::ChunkResponse>> AsyncSubmitQuery(::grpc::ClientContext* context, const ::mini2::QueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mini2::ChunkResponse>>(AsyncSubmitQueryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mini2::ChunkResponse>> PrepareAsyncSubmitQuery(::grpc::ClientContext* context, const ::mini2::QueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mini2::ChunkResponse>>(PrepareAsyncSubmitQueryRaw(context, request, cq));
    }
    ::grpc::Status FetchChunk(::grpc::ClientContext* context, const ::mini2::ChunkRequest& request, ::mini2::ChunkResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mini2::ChunkResponse>> AsyncFetchChunk(::grpc::ClientContext* context, const ::mini2::ChunkRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mini2::ChunkResponse>>(AsyncFetchChunkRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mini2::ChunkResponse>> PrepareAsyncFetchChunk(::grpc::ClientContext* context, const ::mini2::ChunkRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mini2::ChunkResponse>>(PrepareAsyncFetchChunkRaw(context, request, cq));
    }
    ::grpc::Status ForwardQuery(::grpc::ClientContext* context, const ::mini2::ForwardRequest& request, ::mini2::ForwardResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mini2::ForwardResponse>> AsyncForwardQuery(::grpc::ClientContext* context, const ::mini2::ForwardRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mini2::ForwardResponse>>(AsyncForwardQueryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mini2::ForwardResponse>> PrepareAsyncForwardQuery(::grpc::ClientContext* context, const ::mini2::ForwardRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mini2::ForwardResponse>>(PrepareAsyncForwardQueryRaw(context, request, cq));
    }
    ::grpc::Status CancelQuery(::grpc::ClientContext* context, const ::mini2::CancelRequest& request, ::mini2::CancelResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mini2::CancelResponse>> AsyncCancelQuery(::grpc::ClientContext* context, const ::mini2::CancelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mini2::CancelResponse>>(AsyncCancelQueryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mini2::CancelResponse>> PrepareAsyncCancelQuery(::grpc::ClientContext* context, const ::mini2::CancelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mini2::CancelResponse>>(PrepareAsyncCancelQueryRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SubmitQuery(::grpc::ClientContext* context, const ::mini2::QueryRequest* request, ::mini2::ChunkResponse* response, std::function<void(::grpc::Status)>) override;
      void SubmitQuery(::grpc::ClientContext* context, const ::mini2::QueryRequest* request, ::mini2::ChunkResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void FetchChunk(::grpc::ClientContext* context, const ::mini2::ChunkRequest* request, ::mini2::ChunkResponse* response, std::function<void(::grpc::Status)>) override;
      void FetchChunk(::grpc::ClientContext* context, const ::mini2::ChunkRequest* request, ::mini2::ChunkResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ForwardQuery(::grpc::ClientContext* context, const ::mini2::ForwardRequest* request, ::mini2::ForwardResponse* response, std::function<void(::grpc::Status)>) override;
      void ForwardQuery(::grpc::ClientContext* context, const ::mini2::ForwardRequest* request, ::mini2::ForwardResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void CancelQuery(::grpc::ClientContext* context, const ::mini2::CancelRequest* request, ::mini2::CancelResponse* response, std::function<void(::grpc::Status)>) override;
      void CancelQuery(::grpc::ClientContext* context, const ::mini2::CancelRequest* request, ::mini2::CancelResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::mini2::ChunkResponse>* AsyncSubmitQueryRaw(::grpc::ClientContext* context, const ::mini2::QueryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mini2::ChunkResponse>* PrepareAsyncSubmitQueryRaw(::grpc::ClientContext* context, const ::mini2::QueryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mini2::ChunkResponse>* AsyncFetchChunkRaw(::grpc::ClientContext* context, const ::mini2::ChunkRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mini2::ChunkResponse>* PrepareAsyncFetchChunkRaw(::grpc::ClientContext* context, const ::mini2::ChunkRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mini2::ForwardResponse>* AsyncForwardQueryRaw(::grpc::ClientContext* context, const ::mini2::ForwardRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mini2::ForwardResponse>* PrepareAsyncForwardQueryRaw(::grpc::ClientContext* context, const ::mini2::ForwardRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mini2::CancelResponse>* AsyncCancelQueryRaw(::grpc::ClientContext* context, const ::mini2::CancelRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mini2::CancelResponse>* PrepareAsyncCancelQueryRaw(::grpc::ClientContext* context, const ::mini2::CancelRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SubmitQuery_;
    const ::grpc::internal::RpcMethod rpcmethod_FetchChunk_;
    const ::grpc::internal::RpcMethod rpcmethod_ForwardQuery_;
    const ::grpc::internal::RpcMethod rpcmethod_CancelQuery_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SubmitQuery(::grpc::ServerContext* context, const ::mini2::QueryRequest* request, ::mini2::ChunkResponse* response);
    virtual ::grpc::Status FetchChunk(::grpc::ServerContext* context, const ::mini2::ChunkRequest* request, ::mini2::ChunkResponse* response);
    virtual ::grpc::Status ForwardQuery(::grpc::ServerContext* context, const ::mini2::ForwardRequest* request, ::mini2::ForwardResponse* response);
    virtual ::grpc::Status CancelQuery(::grpc::ServerContext* context, const ::mini2::CancelRequest* request, ::mini2::CancelResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SubmitQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SubmitQuery() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SubmitQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitQuery(::grpc::ServerContext* /*context*/, const ::mini2::QueryRequest* /*request*/, ::mini2::ChunkResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubmitQuery(::grpc::ServerContext* context, ::mini2::QueryRequest* request, ::grpc::ServerAsyncResponseWriter< ::mini2::ChunkResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_FetchChunk : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FetchChunk() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_FetchChunk() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchChunk(::grpc::ServerContext* /*context*/, const ::mini2::ChunkRequest* /*request*/, ::mini2::ChunkResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFetchChunk(::grpc::ServerContext* context, ::mini2::ChunkRequest* request, ::grpc::ServerAsyncResponseWriter< ::mini2::ChunkResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ForwardQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ForwardQuery() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_ForwardQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ForwardQuery(::grpc::ServerContext* /*context*/, const ::mini2::ForwardRequest* /*request*/, ::mini2::ForwardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestForwardQuery(::grpc::ServerContext* context, ::mini2::ForwardRequest* request, ::grpc::ServerAsyncResponseWriter< ::mini2::ForwardResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CancelQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CancelQuery() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_CancelQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelQuery(::grpc::ServerContext* /*context*/, const ::mini2::CancelRequest* /*request*/, ::mini2::CancelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCancelQuery(::grpc::ServerContext* context, ::mini2::CancelRequest* request, ::grpc::ServerAsyncResponseWriter< ::mini2::CancelResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SubmitQuery<WithAsyncMethod_FetchChunk<WithAsyncMethod_ForwardQuery<WithAsyncMethod_CancelQuery<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SubmitQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SubmitQuery() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::mini2::QueryRequest, ::mini2::ChunkResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mini2::QueryRequest* request, ::mini2::ChunkResponse* response) { return this->SubmitQuery(context, request, response); }));}
    void SetMessageAllocatorFor_SubmitQuery(
        ::grpc::MessageAllocator< ::mini2::QueryRequest, ::mini2::ChunkResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::mini2::QueryRequest, ::mini2::ChunkResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SubmitQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitQuery(::grpc::ServerContext* /*context*/, const ::mini2::QueryRequest* /*request*/, ::mini2::ChunkResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SubmitQuery(
      ::grpc::CallbackServerContext* /*context*/, const ::mini2::QueryRequest* /*request*/, ::mini2::ChunkResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_FetchChunk : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_FetchChunk() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::mini2::ChunkRequest, ::mini2::ChunkResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mini2::ChunkRequest* request, ::mini2::ChunkResponse* response) { return this->FetchChunk(context, request, response); }));}
    void SetMessageAllocatorFor_FetchChunk(
        ::grpc::MessageAllocator< ::mini2::ChunkRequest, ::mini2::ChunkResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::mini2::ChunkRequest, ::mini2::ChunkResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_FetchChunk() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchChunk(::grpc::ServerContext* /*context*/, const ::mini2::ChunkRequest* /*request*/, ::mini2::ChunkResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FetchChunk(
      ::grpc::CallbackServerContext* /*context*/, const ::mini2::ChunkRequest* /*request*/, ::mini2::ChunkResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ForwardQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ForwardQuery() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::mini2::ForwardRequest, ::mini2::ForwardResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mini2::ForwardRequest* request, ::mini2::ForwardResponse* response) { return this->ForwardQuery(context, request, response); }));}
    void SetMessageAllocatorFor_ForwardQuery(
        ::grpc::MessageAllocator< ::mini2::ForwardRequest, ::mini2::ForwardResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::mini2::ForwardRequest, ::mini2::ForwardResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ForwardQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ForwardQuery(::grpc::ServerContext* /*context*/, const ::mini2::ForwardRequest* /*request*/, ::mini2::ForwardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ForwardQuery(
      ::grpc::CallbackServerContext* /*context*/, const ::mini2::ForwardRequest* /*request*/, ::mini2::ForwardResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_CancelQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CancelQuery() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::mini2::CancelRequest, ::mini2::CancelResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mini2::CancelRequest* request, ::mini2::CancelResponse* response) { return this->CancelQuery(context, request, response); }));}
    void SetMessageAllocatorFor_CancelQuery(
        ::grpc::MessageAllocator< ::mini2::CancelRequest, ::mini2::CancelResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::mini2::CancelRequest, ::mini2::CancelResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CancelQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelQuery(::grpc::ServerContext* /*context*/, const ::mini2::CancelRequest* /*request*/, ::mini2::CancelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CancelQuery(
      ::grpc::CallbackServerContext* /*context*/, const ::mini2::CancelRequest* /*request*/, ::mini2::CancelResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SubmitQuery<WithCallbackMethod_FetchChunk<WithCallbackMethod_ForwardQuery<WithCallbackMethod_CancelQuery<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SubmitQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SubmitQuery() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SubmitQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitQuery(::grpc::ServerContext* /*context*/, const ::mini2::QueryRequest* /*request*/, ::mini2::ChunkResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_FetchChunk : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FetchChunk() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_FetchChunk() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchChunk(::grpc::ServerContext* /*context*/, const ::mini2::ChunkRequest* /*request*/, ::mini2::ChunkResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ForwardQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ForwardQuery() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_ForwardQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ForwardQuery(::grpc::ServerContext* /*context*/, const ::mini2::ForwardRequest* /*request*/, ::mini2::ForwardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CancelQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CancelQuery() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_CancelQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelQuery(::grpc::ServerContext* /*context*/, const ::mini2::CancelRequest* /*request*/, ::mini2::CancelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SubmitQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SubmitQuery() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SubmitQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitQuery(::grpc::ServerContext* /*context*/, const ::mini2::QueryRequest* /*request*/, ::mini2::ChunkResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubmitQuery(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_FetchChunk : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FetchChunk() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_FetchChunk() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchChunk(::grpc::ServerContext* /*context*/, const ::mini2::ChunkRequest* /*request*/, ::mini2::ChunkResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFetchChunk(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ForwardQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ForwardQuery() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_ForwardQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ForwardQuery(::grpc::ServerContext* /*context*/, const ::mini2::ForwardRequest* /*request*/, ::mini2::ForwardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestForwardQuery(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_CancelQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CancelQuery() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_CancelQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelQuery(::grpc::ServerContext* /*context*/, const ::mini2::CancelRequest* /*request*/, ::mini2::CancelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCancelQuery(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SubmitQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SubmitQuery() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SubmitQuery(context, request, response); }));
    }
    ~WithRawCallbackMethod_SubmitQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitQuery(::grpc::ServerContext* /*context*/, const ::mini2::QueryRequest* /*request*/, ::mini2::ChunkResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SubmitQuery(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_FetchChunk : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_FetchChunk() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FetchChunk(context, request, response); }));
    }
    ~WithRawCallbackMethod_FetchChunk() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchChunk(::grpc::ServerContext* /*context*/, const ::mini2::ChunkRequest* /*request*/, ::mini2::ChunkResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FetchChunk(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ForwardQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ForwardQuery() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ForwardQuery(context, request, response); }));
    }
    ~WithRawCallbackMethod_ForwardQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ForwardQuery(::grpc::ServerContext* /*context*/, const ::mini2::ForwardRequest* /*request*/, ::mini2::ForwardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ForwardQuery(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CancelQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CancelQuery() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CancelQuery(context, request, response); }));
    }
    ~WithRawCallbackMethod_CancelQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelQuery(::grpc::ServerContext* /*context*/, const ::mini2::CancelRequest* /*request*/, ::mini2::CancelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CancelQuery(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SubmitQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SubmitQuery() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mini2::QueryRequest, ::mini2::ChunkResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::mini2::QueryRequest, ::mini2::ChunkResponse>* streamer) {
                       return this->StreamedSubmitQuery(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SubmitQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SubmitQuery(::grpc::ServerContext* /*context*/, const ::mini2::QueryRequest* /*request*/, ::mini2::ChunkResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSubmitQuery(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mini2::QueryRequest,::mini2::ChunkResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FetchChunk : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FetchChunk() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mini2::ChunkRequest, ::mini2::ChunkResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::mini2::ChunkRequest, ::mini2::ChunkResponse>* streamer) {
                       return this->StreamedFetchChunk(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FetchChunk() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FetchChunk(::grpc::ServerContext* /*context*/, const ::mini2::ChunkRequest* /*request*/, ::mini2::ChunkResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFetchChunk(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mini2::ChunkRequest,::mini2::ChunkResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ForwardQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ForwardQuery() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mini2::ForwardRequest, ::mini2::ForwardResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::mini2::ForwardRequest, ::mini2::ForwardResponse>* streamer) {
                       return this->StreamedForwardQuery(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ForwardQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ForwardQuery(::grpc::ServerContext* /*context*/, const ::mini2::ForwardRequest* /*request*/, ::mini2::ForwardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedForwardQuery(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mini2::ForwardRequest,::mini2::ForwardResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CancelQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CancelQuery() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mini2::CancelRequest, ::mini2::CancelResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::mini2::CancelRequest, ::mini2::CancelResponse>* streamer) {
                       return this->StreamedCancelQuery(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CancelQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CancelQuery(::grpc::ServerContext* /*context*/, const ::mini2::CancelRequest* /*request*/, ::mini2::CancelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCancelQuery(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mini2::CancelRequest,::mini2::CancelResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SubmitQuery<WithStreamedUnaryMethod_FetchChunk<WithStreamedUnaryMethod_ForwardQuery<WithStreamedUnaryMethod_CancelQuery<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SubmitQuery<WithStreamedUnaryMethod_FetchChunk<WithStreamedUnaryMethod_ForwardQuery<WithStreamedUnaryMethod_CancelQuery<Service > > > > StreamedService;
};

// MgmtService is a separate logical channel for status and heartbeat,
// keeping management traffic out of the data service queue.
class MgmtService final {
 public:
  static constexpr char const* service_full_name() {
    return "mini2.MgmtService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetStatus(::grpc::ClientContext* context, const ::mini2::StatusRequest& request, ::mini2::StatusResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mini2::StatusResponse>> AsyncGetStatus(::grpc::ClientContext* context, const ::mini2::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mini2::StatusResponse>>(AsyncGetStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mini2::StatusResponse>> PrepareAsyncGetStatus(::grpc::ClientContext* context, const ::mini2::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mini2::StatusResponse>>(PrepareAsyncGetStatusRaw(context, request, cq));
    }
    virtual ::grpc::Status Heartbeat(::grpc::ClientContext* context, const ::mini2::HeartbeatRequest& request, ::mini2::HeartbeatResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mini2::HeartbeatResponse>> AsyncHeartbeat(::grpc::ClientContext* context, const ::mini2::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mini2::HeartbeatResponse>>(AsyncHeartbeatRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mini2::HeartbeatResponse>> PrepareAsyncHeartbeat(::grpc::ClientContext* context, const ::mini2::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mini2::HeartbeatResponse>>(PrepareAsyncHeartbeatRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetStatus(::grpc::ClientContext* context, const ::mini2::StatusRequest* request, ::mini2::StatusResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetStatus(::grpc::ClientContext* context, const ::mini2::StatusRequest* request, ::mini2::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Heartbeat(::grpc::ClientContext* context, const ::mini2::HeartbeatRequest* request, ::mini2::HeartbeatResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Heartbeat(::grpc::ClientContext* context, const ::mini2::HeartbeatRequest* request, ::mini2::HeartbeatResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mini2::StatusResponse>* AsyncGetStatusRaw(::grpc::ClientContext* context, const ::mini2::StatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mini2::StatusResponse>* PrepareAsyncGetStatusRaw(::grpc::ClientContext* context, const ::mini2::StatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mini2::HeartbeatResponse>* AsyncHeartbeatRaw(::grpc::ClientContext* context, const ::mini2::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mini2::HeartbeatResponse>* PrepareAsyncHeartbeatRaw(::grpc::ClientContext* context, const ::mini2::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetStatus(::grpc::ClientContext* context, const ::mini2::StatusRequest& request, ::mini2::StatusResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mini2::StatusResponse>> AsyncGetStatus(::grpc::ClientContext* context, const ::mini2::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mini2::StatusResponse>>(AsyncGetStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mini2::StatusResponse>> PrepareAsyncGetStatus(::grpc::ClientContext* context, const ::mini2::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mini2::StatusResponse>>(PrepareAsyncGetStatusRaw(context, request, cq));
    }
    ::grpc::Status Heartbeat(::grpc::ClientContext* context, const ::mini2::HeartbeatRequest& request, ::mini2::HeartbeatResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mini2::HeartbeatResponse>> AsyncHeartbeat(::grpc::ClientContext* context, const ::mini2::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mini2::HeartbeatResponse>>(AsyncHeartbeatRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mini2::HeartbeatResponse>> PrepareAsyncHeartbeat(::grpc::ClientContext* context, const ::mini2::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mini2::HeartbeatResponse>>(PrepareAsyncHeartbeatRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetStatus(::grpc::ClientContext* context, const ::mini2::StatusRequest* request, ::mini2::StatusResponse* response, std::function<void(::grpc::Status)>) override;
      void GetStatus(::grpc::ClientContext* context, const ::mini2::StatusRequest* request, ::mini2::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Heartbeat(::grpc::ClientContext* context, const ::mini2::HeartbeatRequest* request, ::mini2::HeartbeatResponse* response, std::function<void(::grpc::Status)>) override;
      void Heartbeat(::grpc::ClientContext* context, const ::mini2::HeartbeatRequest* request, ::mini2::HeartbeatResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::mini2::StatusResponse>* AsyncGetStatusRaw(::grpc::ClientContext* context, const ::mini2::StatusRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mini2::StatusResponse>* PrepareAsyncGetStatusRaw(::grpc::ClientContext* context, const ::mini2::StatusRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mini2::HeartbeatResponse>* AsyncHeartbeatRaw(::grpc::ClientContext* context, const ::mini2::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mini2::HeartbeatResponse>* PrepareAsyncHeartbeatRaw(::grpc::ClientContext* context, const ::mini2::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetStatus_;
    const ::grpc::internal::RpcMethod rpcmethod_Heartbeat_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetStatus(::grpc::ServerContext* context, const ::mini2::StatusRequest* request, ::mini2::StatusResponse* response);
    virtual ::grpc::Status Heartbeat(::grpc::ServerContext* context, const ::mini2::HeartbeatRequest* request, ::mini2::HeartbeatResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetStatus() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStatus(::grpc::ServerContext* /*context*/, const ::mini2::StatusRequest* /*request*/, ::mini2::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetStatus(::grpc::ServerContext* context, ::mini2::StatusRequest* request, ::grpc::ServerAsyncResponseWriter< ::mini2::StatusResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Heartbeat() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::mini2::HeartbeatRequest* /*request*/, ::mini2::HeartbeatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHeartbeat(::grpc::ServerContext* context, ::mini2::HeartbeatRequest* request, ::grpc::ServerAsyncResponseWriter< ::mini2::HeartbeatResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetStatus<WithAsyncMethod_Heartbeat<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetStatus() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::mini2::StatusRequest, ::mini2::StatusResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mini2::StatusRequest* request, ::mini2::StatusResponse* response) { return this->GetStatus(context, request, response); }));}
    void SetMessageAllocatorFor_GetStatus(
        ::grpc::MessageAllocator< ::mini2::StatusRequest, ::mini2::StatusResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::mini2::StatusRequest, ::mini2::StatusResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStatus(::grpc::ServerContext* /*context*/, const ::mini2::StatusRequest* /*request*/, ::mini2::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::mini2::StatusRequest* /*request*/, ::mini2::StatusResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Heartbeat() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::mini2::HeartbeatRequest, ::mini2::HeartbeatResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mini2::HeartbeatRequest* request, ::mini2::HeartbeatResponse* response) { return this->Heartbeat(context, request, response); }));}
    void SetMessageAllocatorFor_Heartbeat(
        ::grpc::MessageAllocator< ::mini2::HeartbeatRequest, ::mini2::HeartbeatResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::mini2::HeartbeatRequest, ::mini2::HeartbeatResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::mini2::HeartbeatRequest* /*request*/, ::mini2::HeartbeatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Heartbeat(
      ::grpc::CallbackServerContext* /*context*/, const ::mini2::HeartbeatRequest* /*request*/, ::mini2::HeartbeatResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetStatus<WithCallbackMethod_Heartbeat<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetStatus() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStatus(::grpc::ServerContext* /*context*/, const ::mini2::StatusRequest* /*request*/, ::mini2::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Heartbeat() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::mini2::HeartbeatRequest* /*request*/, ::mini2::HeartbeatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetStatus() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStatus(::grpc::ServerContext* /*context*/, const ::mini2::StatusRequest* /*request*/, ::mini2::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Heartbeat() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::mini2::HeartbeatRequest* /*request*/, ::mini2::HeartbeatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHeartbeat(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetStatus() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetStatus(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStatus(::grpc::ServerContext* /*context*/, const ::mini2::StatusRequest* /*request*/, ::mini2::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Heartbeat() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Heartbeat(context, request, response); }));
    }
    ~WithRawCallbackMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::mini2::HeartbeatRequest* /*request*/, ::mini2::HeartbeatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Heartbeat(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetStatus() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mini2::StatusRequest, ::mini2::StatusResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::mini2::StatusRequest, ::mini2::StatusResponse>* streamer) {
                       return this->StreamedGetStatus(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetStatus(::grpc::ServerContext* /*context*/, const ::mini2::StatusRequest* /*request*/, ::mini2::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetStatus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mini2::StatusRequest,::mini2::StatusResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Heartbeat() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mini2::HeartbeatRequest, ::mini2::HeartbeatResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::mini2::HeartbeatRequest, ::mini2::HeartbeatResponse>* streamer) {
                       return this->StreamedHeartbeat(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::mini2::HeartbeatRequest* /*request*/, ::mini2::HeartbeatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHeartbeat(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mini2::HeartbeatRequest,::mini2::HeartbeatResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetStatus<WithStreamedUnaryMethod_Heartbeat<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetStatus<WithStreamedUnaryMethod_Heartbeat<Service > > StreamedService;
};

}  // namespace mini2


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_mini2_2eproto__INCLUDED
