# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mini2_pb2 as mini2__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mini2_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitQuery = channel.unary_unary(
                '/mini2.NodeService/SubmitQuery',
                request_serializer=mini2__pb2.QueryRequest.SerializeToString,
                response_deserializer=mini2__pb2.ChunkResponse.FromString,
                _registered_method=True)
        self.FetchChunk = channel.unary_unary(
                '/mini2.NodeService/FetchChunk',
                request_serializer=mini2__pb2.ChunkRequest.SerializeToString,
                response_deserializer=mini2__pb2.ChunkResponse.FromString,
                _registered_method=True)
        self.ForwardQuery = channel.unary_unary(
                '/mini2.NodeService/ForwardQuery',
                request_serializer=mini2__pb2.ForwardRequest.SerializeToString,
                response_deserializer=mini2__pb2.ForwardResponse.FromString,
                _registered_method=True)
        self.CancelQuery = channel.unary_unary(
                '/mini2.NodeService/CancelQuery',
                request_serializer=mini2__pb2.CancelRequest.SerializeToString,
                response_deserializer=mini2__pb2.CancelResponse.FromString,
                _registered_method=True)


class NodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForwardQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitQuery,
                    request_deserializer=mini2__pb2.QueryRequest.FromString,
                    response_serializer=mini2__pb2.ChunkResponse.SerializeToString,
            ),
            'FetchChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchChunk,
                    request_deserializer=mini2__pb2.ChunkRequest.FromString,
                    response_serializer=mini2__pb2.ChunkResponse.SerializeToString,
            ),
            'ForwardQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ForwardQuery,
                    request_deserializer=mini2__pb2.ForwardRequest.FromString,
                    response_serializer=mini2__pb2.ForwardResponse.SerializeToString,
            ),
            'CancelQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelQuery,
                    request_deserializer=mini2__pb2.CancelRequest.FromString,
                    response_serializer=mini2__pb2.CancelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mini2.NodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mini2.NodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mini2.NodeService/SubmitQuery',
            mini2__pb2.QueryRequest.SerializeToString,
            mini2__pb2.ChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mini2.NodeService/FetchChunk',
            mini2__pb2.ChunkRequest.SerializeToString,
            mini2__pb2.ChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForwardQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mini2.NodeService/ForwardQuery',
            mini2__pb2.ForwardRequest.SerializeToString,
            mini2__pb2.ForwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mini2.NodeService/CancelQuery',
            mini2__pb2.CancelRequest.SerializeToString,
            mini2__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MgmtServiceStub(object):
    """MgmtService is a separate logical channel for status and heartbeat,
    keeping management traffic out of the data service queue.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/mini2.MgmtService/GetStatus',
                request_serializer=mini2__pb2.StatusRequest.SerializeToString,
                response_deserializer=mini2__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/mini2.MgmtService/Heartbeat',
                request_serializer=mini2__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=mini2__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class MgmtServiceServicer(object):
    """MgmtService is a separate logical channel for status and heartbeat,
    keeping management traffic out of the data service queue.
    """

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MgmtServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=mini2__pb2.StatusRequest.FromString,
                    response_serializer=mini2__pb2.StatusResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=mini2__pb2.HeartbeatRequest.FromString,
                    response_serializer=mini2__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mini2.MgmtService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mini2.MgmtService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MgmtService(object):
    """MgmtService is a separate logical channel for status and heartbeat,
    keeping management traffic out of the data service queue.
    """

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mini2.MgmtService/GetStatus',
            mini2__pb2.StatusRequest.SerializeToString,
            mini2__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mini2.MgmtService/Heartbeat',
            mini2__pb2.HeartbeatRequest.SerializeToString,
            mini2__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
